name: 出張申請
description: "出張の許可および日当の承認申請を行います。"
title: "[出張] "
labels: ["approval:pending", "cat:travel"]
body:
  # 1. 目的・概要
  - type: input
    id: summary
    attributes:
      label: "出張の目的 (Purpose)"
      placeholder: "例: NYカンファレンス (TechCrunch Disrupt 202X) 参加のため"
    validations:
      required: true

  # 2. 目的地
  - type: input
    id: destination
    attributes:
      label: "目的地 (Destination)"
      placeholder: "例: アメリカ合衆国 ニューヨーク州、サンフランシスコ"
    validations:
      required: true

  # 3. 日程
  - type: input
    id: dates
    attributes:
      label: "日程 (Dates)"
      placeholder: "例: 202X/10/01 〜 202X/10/05 (3泊5日)"
    validations:
      required: true

  # 4. 費用概算
  - type: textarea
    id: cost
    attributes:
      label: "費用概算 (Estimated Cost)"
      description: "交通費、宿泊費の概算を記載してください。"
      placeholder: |
        - 航空券: 約 250,000円
        - 宿泊費: 約 100,000円 ($200 x 3泊)
        - その他: 約 20,000円 (現地移動費など)
        -------------------------
        合計: 約 370,000円
      render: markdown
    validations:
      required: true

  # 5. 日当の要否
  - type: dropdown
    id: allowance
    attributes:
      label: "日当の要否 (Daily Allowance)"
      description: "食事が提供されるイベントや、全食事が交際費となる場合等は「辞退」を選択してください。"
      options:
        - "支給を希望する (Request)"
        - "辞退する (Decline - 食事支給あり/全額交際費等)"
    validations:
      required: true

  # 6. 詳細・行動予定
  - type: textarea
    id: details
    attributes:
      label: "詳細・行動予定 (Itinerary)"
      description: "主な訪問先やスケジュール、特記事項があれば記載してください。"
      placeholder: |
        10/01: 移動 (TYO -> JFK)
        10/02: カンファレンス参加、〇〇社とミーティング
        10/03: 現地視察
        10/04: 移動 (JFK -> TYO)
    validations:
      required: false

  # 7. 確認事項
  - type: checkboxes
    id: check
    attributes:
      label: "確認事項"
      options:
        - label: "旅費規程を確認し、適切な航空券・宿泊先を選定しました"
          required: true
        - label: "海外出張の場合、必要な海外旅行保険の手配を確認しました（カード付帯等含む）"
          required: true
